admin_password: ${WCAN_ADMIN_PWD:-}
app_name: 编舟文心
count: 10
db: sqlite:///data/articles.db
interval: 10
max_page: 5
notice:
  email:
    smtp_from: ''
    smtp_host: ''
    smtp_password: ${SMTP_PASSWORD:-}
    smtp_port: 465
    smtp_security: ssl
    smtp_to: ''
    smtp_user: ''
  webhook: ''
  wechat: ''
rss:
  add_cover: false
  base_url: ''
  full_context: false
  local: true
  page_size: 30
secret: ${WCAN_SECRET:-}
server:
  auth_web: false
  enable_job: true
  name: 编舟文心
  web_name: 网编部二级网站管理工具
storage:
  base_dir: ''
storage_year: ''
sync_interval: 10
token_expire_minutes: 4320
token_reminder_hours: 12
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
version: 6.0.3
